name: release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["zip"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Freemius
        uses: buttonizer/freemius-deploy@v0.1.2
        with:
          file_name: plugin.zip
          release_mode: pending
          version: ${{ github.event.release.tag_name }}
          sandbox: false
        env:
          PUBLIC_KEY: ${{ secrets.FS_PUBLIC_KEY }}
          DEV_ID: ${{ secrets.FS_DEV_ID }}
          SECRET_KEY: ${{ secrets.FS_SECRET_KEY }}
          PLUGIN_SLUG: ${{ secrets.FS_PLUGIN_SLUG }}
          PLUGIN_ID: ${{ secrets.FS_PLUGIN_ID }}
